global.token = {
  employeeToken: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoaW5AbWFpbC5pbiIsImlkIjoiNjQwOWViYmYwNjY3NmY3Mzc1M2NmYjE1Iiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjc4MzcxODMyLCJleHAiOjE2Nzg0NTgyMzJ9.UQah3wmA-uA2Ia09XDemg4eeQarmQVuhENNh2kxOKGQ`,

  customerToken: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVAbWFpbC5pbiIsImlkIjoiNjQwOTc5NDFkMzc3ODUzYjk3YmZmODViIiwicm9sZSI6IkN1c3RvbWVyIiwiaWF0IjoxNjc4MzcxODUyLCJleHAiOjE2Nzg0NTgyNTJ9.LCFjdCZX3KT5w77jaaz5Ug5PKcWzo6WDapfy1Adrl2I`,

  unauthorizedToken: `eyJhbGciOiIJUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvdWllQG1haWwuaW4iLCJpZCI6IjY0MDgyMTYwZjc1ZWNmODViMzlmZWNjYyIsInJvbGUiOiJDdXN0b21lciIsImlhdCI6MTY3ODI1NDQzMiwiZXhwIjoxNjc4MzQwODMyfQ.b6WgQ6LZEmU7OrQfeZGr0OBPoxI9qJC8I9lTO4mZHZU`
};

module.exports = token;
