global.token = {
  employeeToken: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoid2VyIHJldyIsImVtYWlsIjoieUBtYWlsLmluIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjc4NDQ4ODcwfQ.LpGZ8eNYsFXSf__l58OUoEKKIR5YaMyiDNMbSZkiZJM`,

  customerToken: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXNkIGRzYSIsImVtYWlsIjoiYUBtYWlsLmluIiwicm9sZSI6IkN1c3RvbWVyIiwiaWF0IjoxNjc4NDQ3MDgzfQ.Pn5KEshOH8hcKq10MzR_vfoeDgMOi6GUh1HtI_e8Pd4`,

  unauthorizedToken: `eyJhbGciOiIJUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvdWllQG1haWwuaW4iLCJpZCI6IjY0MDgyMTYwZjc1ZWNmODViMzlmZWNjYyIsInJvbGUiOiJDdXN0b21lciIsImlhdCI6MTY3ODI1NDQzMiwiZXhwIjoxNjc4MzQwODMyfQ.b6WgQ6LZEmU7OrQfeZGr0OBPoxI9qJC8I9lTO4mZHZU`
};

module.exports = token;
